CREATE DATABASE FIXBI

USE FIXBI

CREATE TABLE USUARIOS(
	ID_USUARIO INT IDENTITY PRIMARY KEY
	,TIPO_USUARIO VARCHAR(200) NOT NULL
	,EMAIL_USUARIO VARCHAR(200)NOT NULL UNIQUE
	,SENHA_USUARIO VARCHAR(200) NOT NULL DEFAULT(RAND()*10)
);

CREATE TABLE CICLISTAS(
	ID_CICLISTA INT PRIMARY KEY IDENTITY
	,ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID_USUARIO)
	,NOME_CICLISTA VARCHAR(200) NOT NULL
	,TELEFONE_CICLISTA CHAR(14) NOT NULL UNIQUE
	,INFORMACOES_CICLISTA VARCHAR(200)
);

CREATE TABLE MECANICOS(
	ID_MECANICO INT PRIMARY KEY IDENTITY
	,ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID_USUARIO)
	,NOME_MECANICO VARCHAR(250) NOT NULL
	,TELEFONE_MECANICO CHAR(14) NOT NULL UNIQUE
	,INFORMACOES_MECANICO VARCHAR(200) 
);

CREATE TABLE ATENDIMENTOS(
	ID_ATENDIMENTO INT PRIMARY KEY IDENTITY
	,ID_CICLISTA INT FOREIGN KEY REFERENCES CICLISTAS(ID_CICLISTA)
	,ID_MECANICO  INT FOREIGN KEY REFERENCES MECANICOS(ID_MECANICO)
	,DATA_HORARIO DATETIME NOT NULL
	,DESCRICAO_ATENDIMENTO VARCHAR(200)
	,SITUACAO_ATENDIMENTO VARCHAR(200) NOT NULL
);