CREATE DATABASE FIXBI

USE FIXBI

CREATE TABLE TIPO_USUARIOS(
	ID_TIPO_USUARIO INT PRIMARY KEY IDENTITY
	,TIPO_USUARIO VARCHAR(200) NOT NULL
);

INSERT INTO TIPO_USUARIOS VALUES ('Mecanico'),('Ciclista')

SELECT * FROM TIPO_USUARIOS

CREATE TABLE USUARIOS(
	ID_USUARIO INT IDENTITY PRIMARY KEY
	,ID_TIPO_USUARIO INT FOREIGN KEY REFERENCES TIPO_USUARIOS(ID_TIPO_USUARIO)
	,EMAIL_USUARIO VARCHAR(200)NOT NULL UNIQUE
	,SENHA_USUARIO VARCHAR(200) NOT NULL DEFAULT(RAND()*10)
);

INSERT INTO USUARIOS VALUES (1, 'daniel@fixbi.com', '12345')
	,(2, 'mariana@fixbi.com', '12345')
	,(2, 'suely@fixbi.com', '12345')
	,(2, 'correia@fixbi.com', '12345')

SELECT * FROM USUARIOS

CREATE TABLE CICLISTAS(
	ID_CICLISTA INT PRIMARY KEY IDENTITY
	,ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID_USUARIO)
	,NOME_CICLISTA VARCHAR(200) NOT NULL
	,TELEFONE_CICLISTA CHAR(14) NOT NULL UNIQUE
	,INFORMACOES_CICLISTA VARCHAR(200)
);

INSERT INTO CICLISTAS VALUES (2, 'Mariana Santos', '(11)9999-1001', 'Tem uma MTB')
	,(2, 'Suely Santos', '(11)9999-1002', 'Vai comprar nova bike')
	,(3, 'José Santos', '(11)9999-1003', 'Tem uma cargueira')

SELECT * FROM CICLISTAS

CREATE TABLE MECANICOS(
	ID_MECANICO INT PRIMARY KEY IDENTITY
	,ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID_USUARIO)
	,NOME_MECANICO VARCHAR(250) NOT NULL
	,TELEFONE_MECANICO CHAR(14) NOT NULL UNIQUE
	,INFORMACOES_MECANICO VARCHAR(200) 
);

INSERT INTO MECANICOS VALUES (1, 'Daniel Santos', '(11)9999-1000', 'Câmbios')

SELECT * FROM MECANICOS

CREATE ATENDIMENTOS(
	ID_ATENDIMENTO INT PRIMARY KEY IDENTITY
	,ID_CICLISTA INT FOREIGN KEY REFERENCES CICLISTAS(ID_CICLISTA)
	,ID_MECANICO  INT FOREIGN KEY REFERENCES MECANICOS(ID_MECANICO)
	,DATA_HORARIO DATETIME NOT NULL
	,DESCRICAO_ATENDIMENTO VARCHAR(200)
	,SITUACAO_ATENDIMENTO VARCHAR(200) NOT NULL
);

INSERT INTO ATENDIMENTOS VALUES 
(1,	4,'2019-06-26T15:00:00','Pneu furado','Realizada')
,(2,4,'2019-06-27T16:00:00','Regulagem de freio',	'Agendada')
,(3,4,'2019-06-28T17:00:00','Troca de câmbio','Cancelada')

SELECT * FROM ATENDIMENTOS
